#! /bin/bash
declare -a array				#定义数组array
i=1						#i初始化为1
sum=$1						#sum初始化为命令行第一个参数
max=$1						#max初始化为命令行第一个参数
min=$1                                          #min初始化为命令行第一个参数
array[$i]=$1                                    
for ((i=2;i<=100;i++))
do
	shift 1                                 #将命令行参数左移一位
	array[$i]=$1				#将命令行第i个数存到数组中
	sum=`expr $sum + $1`			#sum累加
	if [ $max -lt $1 ] 			#如果输入的值比max大，则修改max的值
	then 
		max=$1 		
	fi
	if [ $min -gt $1 ] 			#如果输入的值比min小，则修改min的值
	then 
		min=$1 			
	fi
done
echo "max = $max"					#输出最大值
echo "min = $min"					#输出最小值
echo "sum = $sum" 					#输出总和
for ((i=1;i<=100;i++))					#选择排序
do
	for ((j=i+1;j<=100;j++))
	do
		if [ ${array[$i]} -gt ${array[$j]} ]
		then
			temp=${array[$i]}
			array[$i]=${array[$j]}
			array[$j]=$temp
		fi
	done
done
echo "after sort:"
for ((i=1;i<=100;i++))					#输出排序后的数组
do
	echo -n "${array[$i]} "
done
echo
exit 0