#! /bin/bash
chmod +x admin
chmod +x teacher
chmod +x student
clear
while true
do
	echo "           欢迎进入作业管理系统"
	echo "==========================================="
	echo "              请选择操作:"
	echo "              1-管理员"
	echo "              2-教师"
	echo "              3-学生"
	echo "              0-退出"
	echo "==========================================="
	read num
	case $num in
		1)./admin;;
		2)./teacher;;
		3)./student;;
		0)clear
		echo "退出成功！"
		echo "谢谢使用此作业管理系统"
		sleep 1
		while true
		do
			exit
		done;;
		*)echo "请输入正确的数字。"
		sleep 1
		clear;;
	esac
done
